### ISSUE TITLE
Add a section to credit all the contributors, reviewers, advisors.

### ISSUE THREAD

**Issue by reddragon** [EfficientDL/book#6]
We want to credit all the people who have contributed in any capacity to the book and the codelabs. This should include:

1. Reviewers who have reviewed the manuscript.
2. Collaborators who have worked on the manuscript with us / helped with codelabs.
3. Any advisors.

We should capture their help on both the website and the GitHub repository.

**Comment by NareshPS** [comment]
Added https://github.com/EfficientDL/book/blob/main/README.md#reviewers
